--- 
after_success: 
  - "travis-sphinx deploy"

install: 
  - "pip install --user travis-sphinx"
  - "pip install --user sphinx_rtd_theme"
language: "python - \"2.7\""
script: 
  - "travis-sphinx --source=docs/source --pullrequests --branches=test_doc_build build"
  - "travis-sphinx deploy"
